import {RoleEnum} from "../enum/role.enum";
import {HeroModel} from "../model/hero.model";
import {AffiliationEnum} from "../enum/affiliation.enum";
import {SideEnum} from "../enum/side.enum";
import {AttackRangeEnum} from "../enum/attackRange.enum";
import {HeroTypeEnum} from "../enum/hero-type.enum";
import {NumberOfDiceEnum} from "../enum/number-of-dice.enum";
import {ThrowsEnum} from "../enum/throws.enum";

export const Players: HeroModel[] = [
  {
    "id": "17_6Kmol4HJh3bW_RyOBFmVkqI894KRTW",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Iceman",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.SPEED, RoleEnum.CC ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1UXLi5AVp2QuqdbQR82zyX6s5uHm8vOwc",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Cyclops",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION,RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1QBwWSy6u1c8GkkWBKSjpbzVW2MA9rvyZ",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Dark Phoenix",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY, RoleEnum.TANK ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1sHMmpL1aN3DfpkECWlHbSs65vG5OAOmM",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Sabretooth",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1wlyaW5i4Vb202lv-ZWlhg2NIJAXKX-kJ",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Storm",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1TflW7sVCFVGGktNr3VcDInENdMQiwh0Y",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Magneto",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "10YDTE2-KNV3WEg0J4GWb0jsNtt3S5Zyq",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Wolverine",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.TANK ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1zmDLBgIZ6sIAre3PxSUS6JuPIFMS-65C",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Mystique",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1_IxQO7_8dOu29BK0ruHJasEojJblAKd_",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Colossus",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "12kx9WGx28Mqjot6EQEr5D2W-SRgHx1OL",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Rogue",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1eQobDvusdD1JLBq06r-4h1eoHhJij56J",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Psylocke",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1AwyM0yLZbJ7RL09QF7VchZHvHbj9rI0L",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Juggernaut",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "18HuJehbkwjfp5Sez9OmEREZQ3Xy3UoKh",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "She-Hulk",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1e15Et7jE7iasAuQXLMmbrQiZcyFFVoXB",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Thanos",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION,RoleEnum.UTILITY, RoleEnum.CC ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1RVKv1tZPLvbh9Rglv_uo6CzafmW73T6w",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "The Thing",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY, RoleEnum.TANK ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1PDlG4KV7BfDd95ZtKtoaBIIsc1sfTyy7",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Mister Fantastic",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1NBmbJAZssGSY5gmLAEK6TWdRi6_zeQgI",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Scorpion",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1XqWyd0p9zccO2nHtCDHpRksHq8_zAkz1",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Storm",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1j-PGFB0-dEgFuMp3b0llyzC6YgwgWxfa",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Human Torch",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1ASM8h2_HZ1gKih6oQ2UN17IlVndWt2Oq",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Multiple Man",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.SPEED ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1fhvJZHrZS6yMKIP0Jk7cF5wofO-JUt37",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Mystique",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "10GrQpZbLDQ1UoPCqPc_Q-4ygHurylZ_c",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Professor X",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_1,
    "throws": ThrowsEnum.THROWS_2
  },
  {
    "id": "1JvilXJ4lld3-zWGI8acubPkHGw8lBF6f",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Black Widow",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "14JIRNAVZRMdeCOE4uS6ejPUilasC6QTg",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Mantis",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },{
    "id": "1M6clDn_7TgmH3Qw7uF0mcWkZvXM8OUW3",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Invisible Woman",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1QzkcsVfDuYpM0-2jTpGKkf0fbLjyvqqs",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Mysterio",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC,RoleEnum.DMG_BOOST, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1zBItvTzh_jPrWCWh1ycOVHcdshjL7Jzk",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Venom",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1O3KJpbChc3Jk9plIYThMServMAXq4aNp",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Kingpin",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION, RoleEnum.CC ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1q0Df-4TzvEOob64nElef1rxzBmP2TOEs",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Wolverine",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.TANK ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1bzz1HvFupZdJx7lHwVebCa33AigqlSWL",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Winter Soldier",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1yWbyuKDX_z-rwSKYmYkvdDaJ_X3nPznt",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Thor",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.SPEED ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1NDFfC8j2XRLdiGX-d16khyoyYu-j1i1F",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Scarlet Witch",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1781xsjNwxuQ5tDjdrBmeDqJGmOSEEjB7",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Rogue",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1XnGUaQWMpjpxWnTO5xnnrCW2Hh4fiGFl",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Nova",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1zMFAEPwjTOMGZVXNutmCgDYYUU0nlAvy",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Nightcrawler",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1jnWoXMbpIB9rHN7k0f8yEKtj8bpomhPe",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Ms. Marvel",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },{
    "id": "1JB0aFkGo9KxZvZr7ChVRzXq_uDtT_W4c",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Moon Knight",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1WZPoeF4tJhSiq_6IIsst_ZbXGfQthFu5",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Magneto",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION,RoleEnum.CC, RoleEnum.DMG_BOOST, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1g9I71wGhUWhMfessmmTa3J4Ug1qQQIID",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Luke Cage",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1gjxskB7B_2JJsaPzYS-REzlUgalB1VxB",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Kraven",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.SPEED ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "12Vanprq6_6DnlEDl4taRmiWbll4CUPOj",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Daredevil",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.CC, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1fUOgNb1royKRPR7dKGxYC5iJgY0P4vFz",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Doctor Strange",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1vEgpjHyxV-pnzyIdqXA0MIwjUTDeHmWo",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Giant-man",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1iyw3WZJZFvftpK1G2DcUa0HVkHbBiZrP",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Gamora",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.SPEED, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1tq8lI9wm4yi-jLEzSampTlIUHzLnvDmX",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Gambit",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST, RoleEnum.UTILITY ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1lGH8kumXSrph2CnoaHl6VDFWMSzuhIKy",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Elektra",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "111CS8932BgEoSOid24pkW1sdEPTVDLAD",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Colossus",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST, RoleEnum.CC ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1j4jXDIPKWe7ePxOKv4H5QsXnrMlDdfsd",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Bullseye",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },{
    "id": "1hko_yLIUtK_lRupHXuNlxPxVTdCwpM2p",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Black Cat",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1kO98LGuwJVwpn5jV7Rl8xU9r4n1fbJX2",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Beast",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  }

  ,
  {
    "id": "1yt6E4otC5eLb1AhYPwtM_ftm-NPf9taL",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Nebula",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },{
    "id": "19n7Ur1cQvPRKV7rMRHWbm5jo9omUr4T_",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Drax",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1eV3kJj8MxXGXAGxEpCq_DLEVZl5BKFcZ",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Rocket",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1DGy32ARCr3luvUecv64_legm_4PoSdpD",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Star-Lord",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },{
    "id": "1VV2lKE7mT7Llr_1MLMOvqajTuoe-QONz",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Loki",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1QK_qMzUtAUS6bnE9_mBy9MCbcaESu6Qc",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Falcon",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1FzmO0166jkzj0k7RbtbGsYhmDoDwtHey",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Quicksilver",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },{
    "id": "1y999ELhJ9FY2vGjFOZ139cUHmGAES9hD",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Hawkeye",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY, RoleEnum.DMG_BOOST ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1X34lr2hCGiG5esM_dMzeqZLq84uG-lnr",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Green Goblin",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1STQcOEaP5_Q3U-OxktG8wWR9kr823f_o",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Electro",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },{
    "id": "1uWJFzs6cHzpzytGUEOFw2IDOqnIlppy6",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Lizard",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1BWxc9lneNAm-MaKXBYNyrrHG026gr7bD",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Rhino",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1RDW_i_OhVwlVMbXdxPpAr1qNQ_zoALkm",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Doctor Octopus",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },{
    "id": "1jq_cDhzArIUpYMCBGyudvAIh36NqZ9K8",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Vulture",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "17uHroVkCJlOs5VWdGrnygbGPcyamZ7Nm",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Super-Skrull",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1mfvmCmqgEFUz-wz8K2000qDRKASe3ZIc",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Black Bolt",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },{
    "id": "13vAv-Ab3T08Rxww2e4NSLfcmvVaZjDFa",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Namor",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.TANK ],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1dInJD_NJudg5UiXPCmRhmidhL0nKCdZN",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Doctor Doom",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1q0tJlYRSN8SqxpTJ-it1g1WlTZQyzH8T",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Invisible Woman",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST, RoleEnum.CC],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1zo8FGcg2iHnm1CSgkMhn98fEzbIGLnjM",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Human Torch",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1A6Evvf7ST6Ipkbnx5jqOXcFKDA2buqgG",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Rocket",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1KBYmg8L5K0VfaiFXnR_3ZOsklMJ7KYrR",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Drax",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1D084c3Sc8FqsJdRt-RIHLZ2XDMF8qGeD",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Nova",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.TANK, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1c6m_ghWmqzJDLkAcdjfgVSQ4_8hRP5R_",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Mantis",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "10qZ47AB5GI2jI56o9amxS1FMYV8TkEQN",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Groot",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.TANK, RoleEnum.CC],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1WbDSEYGpl4HMPHFch0IxDuw4Zjg4pm9y",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Gamora",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1jpH9VcdQMjeY3FiNKxEpOr9N1ZZDXPXq",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Vision",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1LBhvqZ5KTnhsWsjvvJfZMPuVfJLWeB4V",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Antman",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1_r1cdqWbkvqoLfYiDKnWx4HVaenDocyR",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Black Widow",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1Qxx8ezSwxi5M8HJcFRqR8tHY63AgNBBX",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "She-Hulk",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST, RoleEnum.CC],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1Dmw4whetDySCdEF7CuC1NRMD-UEN6j0c",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Kraven",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "16s5uAlWvH93lyZzkvhyVaod7dhnoWVND",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Venom",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.DMG_BOOST, RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "142glyNlzzLSKCxRV-gbPbOuoIQVuPkC3",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Scorpion",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "13Ub2T-Rm_XwSkCLAMG0YyEO_hNZwFuTc",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Sandman",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1v-Yl3lCwmqQMKIZJS7SEq3KNur4SwUDw",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Mysterio",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1OMEoBgW4ogecjfNLtDqXcoFTBVwur7o-",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Black Cat",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1KEDYVantI70mLixIVlTbYFSXlVYOhB_s",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "The Thing",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1ZVMCsgzuGdfnbU8RQTBt1JJ3JQkQVBL5",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Mister Fantastic",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1mj3iFSbhnfJlpPpMITDYU0rfzSzmDUVz",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Super-Skrull",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.CC],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1tfteh89OgSwCc1wPhCa5g925YSFue_fJ",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Professor X",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_1,
    "throws": ThrowsEnum.THROWS_2
  },
  {
    "id": "1JDrY9qS00TttvSl4ayPlMZXe_o4ehD2E",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Green Goblin",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "15irHBK99X2kQiUEU6VY4h2d4qujnW6En",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Nana",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.UTILITY, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1cKqSvv-9qqVAc_AwjXBnmSOWUghMPbpg",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Rhino",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1HBOqrP1Rw8bgLKDUeDjH0h_4ksvxost5",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Falcon",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1V0ErX0FtWRGHsNa7R4Wsi7RNiKqrprOr",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Nebula",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_2,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "11Vmd3y5-bKG_Cz_TNRr8kf0x860f6HOf",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Red Skull",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_2,
    "role": [ RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_1,
    "throws": ThrowsEnum.THROWS_2
  },
  {
    "id": "15qPt52Fe1y2R1Ui5MxbIsSVZKgr7673S",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Quicksilver",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1XkRsL4jWw5rw7vh_X-TdgYo5bZVtc15S",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Luke Cage",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1dWvll3eWoKytfUmg3Z-6Tp7LGskTmmT7",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Jessica Jones",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.UTILITY, RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1GAOfls4o-U_EbHs-07x7o_mP7ffUr64P",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Namor",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1zSG76WG6OoNYQ_SaRYeHShKNe2BXVrSR",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Nightcrawler",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "14GBDpVamfAOIakzGAYhzfEANBf6Zc04m",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Lizard",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1LDO8fteCVNU1sd5ev6vUIGp5mZPw9wX0",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Loki",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.SPEED, RoleEnum.CC],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1tCwZiC88SDLenkAT4zcsjnjLDZJeenWF",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Morbius",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1M8lswhARIAWihYNeaCRKA05uT1rOuH5J",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Moon Knight",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1Xr2mbTgBwuULsXhAR-qq9OJ5hwzMLWpi",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Miles Morales",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1t8eTYodPZUkDj7THp6fSQt_gFA1vOXh7",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Kitty Pride",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1dBcZPkE60RgEUrUowak0GD3Gd8tOe3A0",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Kingpin",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1PNnAt49hjO--sUAWSOFhSMchsaXm5zAq",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Juggernaut",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1XAaCfZYSL5BaxAfj4Bm6nY7nrxKVayOX",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Iceman",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.CC, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "17BYfdv5GqO1CWOZGiTE7uKa9vlNU8rvV",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Iron man",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1bx4PyBUI8FWpZjoUR5WSECBh_X2qpJNo",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Hulk",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1J2Mqjr6nlBQ_FteqZyhrGfVfLpKbjI68",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Hawkeye",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_2,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_1,
    "throws": ThrowsEnum.THROWS_2
  },
  {
    "id": "1Qo58-tRbcFD8WB-uB5vvUTpcAJXL6UPr",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Gambit",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "18gFWdlF4639vU7CLMQXrr4OGxvi4szON",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Emma Frost",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_1,
    "throws": ThrowsEnum.THROWS_2
  },
  {
    "id": "1Fl2gsz0Pe0U2HfCNKGa3MGRUkz3x7Ykw",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Electro",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1Nh6SXGVBA557YEI4mc7xQugc_J6h8jtM",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Elektra",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "12QXZkZYrGv3q04_BlW80ypFRtTBCZy2W",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Cyclops",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1KLing3YZN0FHuHxhVrxg4N-RLVHmFt5m",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Daredevil",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1NmpP6JYd5aB3zErmQjosShEUDlNk9mxo",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Crossbones",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.CC, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1M1Mm-Beo248atCqIsrN0IQhJbnKbIa1j",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Carnage",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1jnQ9cnZl_E20z_Qw-r58XgW2mp64S3eT",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Captain Marvel",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1TkF7ssAjeSgGyUHjygrEAuwThT3Tz0GY",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Captain America",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "16HLA1FEsD0Jv0w9v8IlEeCVZ3oQsOIgf",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Doctor Octopus",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.CC, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1rVqlKPETj0oxAH-hSBbOfSm28bXSCwvw",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Doctor Doom",
    "affiliation": AffiliationEnum.FANTASTIC_FOUR,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1t-sEGDZU9ZMsO66fHcJiM1qYq0ex3gZR",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Deadpool",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.CC, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1LJnu45MDSg-hTBjfpB30eiYycw1XMh36",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Dark Phoenix",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1npzck6AT7ej3gSWWve823LENce0A8mU-",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Blade",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1BfrlM9fapX9xWW71eEBV7O55VAZupWJy",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Bullseye",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "19tuUzh9XEryKOp4FgzcWjKZGnv4UA8U8",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Black Knight",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1Eg7HFJpm20e30wv-WgT-ejwmK9iw_o-I",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Black Bolt",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1YCyQb-1pzZabQ5rIFYmUsykXos31B1AG",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Beast",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.DMG_BOOST, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1KLyLC0QoWEiPp2gU7O2Fqrp_4UluuUhd",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Baron Zemo",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1rET4RNG2vdvlfoKuvz4UtMljm_INyWPP",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Hulk",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1DKMS5mQAVjQem7rz5J8SJTqHXfW55E3c",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Iron Man",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1c7eyNA4TZyb8qX317BheuDocHyfiMACY",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Deadpool",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1q-PRaCXPgwLyMxBIkzuAowTFLyAmq-YF",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Captain Marvel",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.DMG_BOOST, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "16sEXHdy0QL-AQknR7dbN8CCB6aTJL3US",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Captain America",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "18qiIAWtRa21qIoNxl2bKTPKrr7CHYTb7",
    "heroType": HeroTypeEnum.ZOMBIE,
    "name": "Wasp",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1gd9aGcu_fCqa9nrF3NjYrauVF_n8IiWp",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "War Machine",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "16HOSW9AZsyHms4arJ4xn-oE_jXg3jkTJ",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Wasp",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1ro__UZXJdC3asELwMSxPZPgXmyG5M0Dc",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Winter Soldier",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "11TwolsIk_teokkDndsZxemXYbNpPbsvC",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Ghost Rider",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1FyTYOr_-tdiPQKVrF8QZe2vzvHOpAjDM",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Psylocke",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "15BiAyTphq32kPY0s16LO7haXmj5pnVbZ",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Vulture",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1v56zBHm6084MnfzMZu5WjyMQrYTyPmQH",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Sabretooth",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.SPEED],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1ap25GADOs4o_XoHDsuczluNBmNecLDdR",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Shang-Chi",
    "affiliation": AffiliationEnum.WITHOUT_AFFILIATION,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.TANK, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "11C6x3jbpJLr86UmfNJUkBDnVLzcxKXgt",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Star-Lord",
    "affiliation": AffiliationEnum.GUARDIANS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "11eN8sNsE6cizFWMuY6nKQuSguaziBg6b",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Spider-Woman",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1oTFOzBV9W4JQmZR_TNhQPZgNlXtIrEPG",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Old Man Hawkeye",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1RcRvlgIGZ9s5Cj4zNQl7ndMuq5o0IhWm",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Old Man Wolverine",
    "affiliation": AffiliationEnum.XMEN,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.TANK, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "18NH9J6l5HsxuHt77sfHyUE6tH3FrOf3i",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Daredevil Elektra",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1kFach_4m5tcHLu8XjD1BcxX3stRojKyC",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Marshall Bullseye",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.VILLAIN,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1auu2LvqWxUSqjVRHJds8O3vOuycziv-P",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Daredevil",
    "affiliation": AffiliationEnum.HEROES_FOR_HIRE,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1qzW59ZYoha22YjSZW47uoV9nwrnU0H9C",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Spiderman",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION, RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1yTETfn7Wue2K2oGkdpZ1NJvXH7RonNGy",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Thor",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1l0Qg2Z1Cg0TU0w5R606Epg7u5GSx_hZ5",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Spiderman",
    "affiliation": AffiliationEnum.SPIDERMAN,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.SPEED, RoleEnum.CC, RoleEnum.FREE_ACTION],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "1NuN2mIaA9cB7VBvodG6Jl6j-TffrfQlI",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Scarlet Witch",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY],
    "numberOfDice": NumberOfDiceEnum.DICE_3,
    "throws": ThrowsEnum.THROWS_4
  },
  {
    "id": "19wr2c1qGVA1kBegAK7Ks2OkxRDrN6Vu7",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Ms. Marvel",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.CC, RoleEnum.FREE_ACTION, RoleEnum.TANK, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1kchAQsNrnP_bHBEl9bsX9XEaCGZzH4J5",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Doctor Strange",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.HERO,
    "attackRange": AttackRangeEnum.RANGE_0_1,
    "role": [ RoleEnum.UTILITY, RoleEnum.FREE_ACTION, RoleEnum.DMG_BOOST],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  },
  {
    "id": "1OSq_lgyAQxp8WhizlNduWekba-7swwyd",
    "heroType": HeroTypeEnum.SURVIVOR,
    "name": "Black Panther",
    "affiliation": AffiliationEnum.AVENGERS,
    "side": SideEnum.ANTIHERO,
    "attackRange": AttackRangeEnum.RANGE_0,
    "role": [ RoleEnum.DMG_BOOST, RoleEnum.FREE_ACTION, RoleEnum.TANK],
    "numberOfDice": NumberOfDiceEnum.DICE_2,
    "throws": ThrowsEnum.THROWS_3
  }
]


